### ISSUE TITLE
Stupid Question

### ISSUE THREAD

**Issue by ghost** [ReclaimerShawn/My-Programs#12]
This may looks like a stupid question, but what is the shortcut to open the Super SmashBros cheat menu ? 😅

**Comment by ReclaimerShawn** [comment]
First, launch the plugin by opening NTR CFW Mode 3, then press the Home button and immediately load Super Smash Bros. The plugin from there can then be opened by pressing either X+Y or L+Start and then selecting Game Plugin. You can activate the cheats from there. With the exception of the Fighting Mii Team cheats, only enable the codes after pausing in the middle of a battle. Make sure to disable them before the battle ends, as if this isn't done the game will crash.

**Comment by ghost** [comment]
Oh, wow, thank you 😅
I've been using luma cheats for so long that I forgot NTR existed 😅

Thank you once again, and hopping you'll have a nice day 😊
