### ISSUE TITLE
Has "How to Make Cheats for the Nintendo Switch" series ended?

### ISSUE THREAD

**Issue by ZzzDave** [ReclaimerShawn/My-Programs#13]
So I recently found that on youtube and I find it quite interesting! Tho we didn't get any news since 6 months so I was wondering if the series was ended, because I would like to learn more :D I understand it takes quite a lot of time tho and we all have a life beside internet so, I was just curious about that

Thanks!

**Comment by ReclaimerShawn** [comment]
I don't know if you still watch/see this repository, but I was just lazy and didn't upload anything in the months of my absence. I do not know if I'll make another video after the Pointer Video or not, but I did upload the Pointer tutorial video recently. You may find it here: https://youtu.be/deYoasVMjBw

I will close this issue now.
